name: Android CI
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JVM_OPTS: -Xmx4G

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Restore CCache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 3Gi

      - name: Restore Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('app/**/*.xml') }}-${{ hashFiles('app/**.kt', 'app/**.java') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('app/**/*.xml') }}-
            ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}-
            ${{ runner.os }}-gradle-
      - name: Install Ninja Build
        run: |
          sudo apt-get install -y ninja-build
          ln -s /usr/bin/ninja .
      - name: Install CMake & Android NDK
        run: echo "yes" | $ANDROID_HOME/tools/bin/sdkmanager "cmake;3.22.1" "ndk;25.0.8775105" --channel=3 | grep -v = || true

      - name: Android Assemble
        env:
          CMAKE_C_COMPILER_LAUNCHER: "ccache"
          CMAKE_CXX_COMPILER_LAUNCHER: "ccache"
          CCACHE_NOCOMPRESS: "true"
        run: ./gradlew --stacktrace --configuration-cache --build-cache --parallel --configure-on-demand assembleBitReldebug

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/bit/reldebug
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.STOREPASS }}
          keyPassword: ${{ secrets.KEYPASS }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Retrieve commit identification
        run: |
           GIT_BRANCH=$(git name-rev --name-only HEAD)
           echo "GIT_BRANCH=${GIT_BRANCH}" >> $GITHUB_ENV
           GIT_HASH=$(git rev-parse --short HEAD)
           echo "GIT_HASH=${GIT_HASH}" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v3
        with:
          name: Tagline-${{ env.GIT_HASH }}
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - uses: 8bitDream/action-github-releases@v1.0.0
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "8bit/${{ env.GIT_BRANCH }}"
          prerelease: ${{ env.GIT_BRANCH != 'ftx1' }}
          title: Tagline-${{ env.GIT_HASH }}
          files: ${{steps.sign_app.outputs.signedReleaseFile}}
